### ISSUE TITLE
separate_ fails with zero row data frames

### ISSUE THREAD

**Issue by richierocks** [hadley/tidyr#100]
To reproduce:

    separate_(data.frame(x = character(), y = logical()), "x", "z")
    ## Error in matrix(unlist(pieces), ncol = n, byrow = TRUE) : 
    ##   'data' must be of a vector type, was 'NULL'

Traceback:

    4: matrix(unlist(pieces), ncol = n, byrow = TRUE)
    3: str_split_fixed(value, sep, length(into), extra = extra)
    2: separate_.data.frame(data.frame(x = character(), y = logical()), 
           "x", "z")
    1: separate_(data.frame(x = character(), y = logical()), "x", "z")

I get the same error with `extra = "drop"`.

**Comment by hadley** [comment]
Seems to work ok for me in the dev version.
