### ISSUE TITLE
loading reshape and plyr with dplyr and tidyr 

### ISSUE THREAD

**Issue by mbkranz** [hadley/tidyr#103]
Hi,
 
I loaded reshape and plyr first (as recommended) and then tidyr and dplyr. For some reason, loading reshape does not allow me to name the variable column when I use the gather() function from tidyr. When I do not load reshape, the gather() naming works as intended.

Has anyone had this issue and/or know how I should change my code?

Mike

**Comment by hadley** [comment]
This is fixed in the dev version
