### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by areisin1** [hadley/tidyr#105]
I just updated to R 3.2.2 and downloaded the newest Rstudio as well. I was working through a model that uses the ggmcmc package that has tidyr as a dependency. Unfortunately, when I tried to reinstall the ggmcmc package it wouldn't load because tidyr was not installed. When I try to install tidyr directly I get the following:

> install.packages("tidyr")
Installing package into ‘C:/Users/AJR/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
      binary source needs_compilation
tidyr  0.2.0  0.3.0             FALSE

installing the source package ‘tidyr’

trying URL 'https://cran.rstudio.com/src/contrib/tidyr_0.3.0.tar.gz'
Content type 'application/x-gzip' length 150414 bytes (146 KB)
downloaded 146 KB

* installing *source* package 'tidyr' ...
** package 'tidyr' successfully unpacked and MD5 sums checked
** libs
Warning: running command 'make -f "C:/PROGRA~1/R/R-32~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="tidyr.dll" OBJECTS="RcppExports.o fill.o matrixToDataFrame.o melt.o simplifyPieces.o"' had status 127
ERROR: compilation failed for package 'tidyr'
* removing 'C:/Users/AJR/Documents/R/win-library/3.2/tidyr'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.2/bin/i386/R" CMD INSTALL -l "C:\Users\AJR\Documents\R\win-library\3.2" C:\Users\AJR\AppData\Local\Temp\Rtmp8crEuu/downloaded_packages/tidyr_0.3.0.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘tidyr’ had non-zero exit status

I see that an updated version of the package was just published today, I'm wondering if this is the issue?

**Comment by hadley** [comment]
Yeah, just wait a day or two for the binaries to come out
