### ISSUE TITLE
gather_ no longer supports dropping a column?  

### ISSUE THREAD

**Issue by cboettig** [hadley/tidyr#109]
consider:

```r
df <- data.frame(A = rnorm(10), B = rnorm(1:10), C = 1:10)
tidyr::gather(df, value, variable, -C)
```

I would have thought that something like the following would be a standard-evaluation equivalent:

```r
tidyr::gather_(df, "value", "variable", quote(-C))
```

but this just throws the error

```
Error in match(gather_cols, names(data)) : 
  'match' requires vector arguments
```

Giving this a vector doesn't fix things:

```
tidyr::gather_(df, "value", "variable", list(quote(-C)))
Error: Unknown column names: -C
```

Until the most recent release of `tidyr` (0.3.1) this work-around seemed to work:

```r
i <- which(names(df)=="C")
tidyr::gather_(df, "value", "variable", -i)
```
but no longer. (error is `Unknown column names -3`).    

It appears that `gather_` doesn't have any option such as `.dots` to benefit from the usual NSE work-arounds in the sister dplyr functions...  Maybe I'm just missing something obvious.

**Comment by mamaya881** [comment]
+1

**Comment by josiekre** [comment]
+1

**Comment by hadley** [comment]
`gather_()` only works with character vectors. You can use `dplyr::select_vars` to get the right vector.
