### ISSUE TITLE
develop of extract_numeric function

### ISSUE THREAD

**Issue by Nicolabo** [hadley/tidyr#111]
Hi,
I just have one suggestion to the `extract_numeric` function. Very usually I work with character columns which has more than one numeric value. Sometimes columns have longer strings with more numbers and it will be nice to manage which number you want to extract. 
For my purpose I prepared a function:

`extract_numeric2 <- function(x, which_one = 1){`
`  num <- str_trim(gsub("[^0-9.-]+", " ", x))`
`  num <- strsplit(num," ")`
`  as.numeric(sapply(num,"[",which_one))`
`}`

E.g. your last commit
`extract_numeric2("49b30ea1ee66f66bbb05b6e5c728942566345f33",2) =  30`.

I know that this is extremely simple function but really useful one. I already put it into my private package, but I thought it would be nice if such tidyr-based function would be a part of `tidyr` package.

**Comment by hadley** [comment]
Now I'd recommend using `readr::parse_number()`. If you want something more general, I think you're right to create it yourself.
