### ISSUE TITLE
Loosing data.table class when using complete()

### ISSUE THREAD

**Issue by VadymBoikov** [hadley/tidyr#112]
If I use complete() on a data.table, it loses it's class

    > dt <- data.table( a = LETTERS[1:6], b = 1:6, c = seq(1,3,2))
    > print(class(dt))
    [1] "data.table" "data.frame"
    > complete(dt, a,b) %>% class
    [1] "tbl_df"     "tbl"        "data.frame"

**Comment by hadley** [comment]
I'd be happy to accept a pull request that implements this, but complete data.table support is not a priority until I'm reasonably certain that I have all the necessary verbs for tidyr.

**Comment by eliocamp** [comment]
Hi! I'm sorry to comment on an old, closed issue but encountered just this problem and was wondering what would it be needed to implement data.table support. Is it something that should be implemented in the data.table package as methods to the tidyr generics or it needs to come internally from the tidyr package itself?
