### ISSUE TITLE
fill_up()

### ISSUE THREAD

**Issue by coolbutuseless** [hadley/tidyr#114]
Feature request: A complementary function to fill()  (or even just a flag), that fills upwards.

I currently do this with a rev(zoo::lacf(rev(x))).

**Comment by hadley** [comment]
Can you provide an example where you see this sort of data?

**Comment by coolbutuseless** [comment]
I understand that the fill down is much more common - especially for manually constructed data (like excel spreadsheets) where people enter a value once in a column on the assumption that it is unchanged until the next entry.

I see lots of data - usually after merging - where I want all values filled, but there's no guarantee that the first row contains a value.   

As an example: drug trial data where weight (or other demographic data) might be measured on the second visit, but not the first.  After merging data sets for analysis, the weight needs to be copied up and down within each subject.

I'm probably an outlier here, and fully understand if this feature is not a priority. Thanks.
