### ISSUE TITLE
gather uses make.names on illegal column names

### ISSUE THREAD

**Issue by markriseley** [hadley/tidyr#115]
gather/gather_ returns results where illegal column names in keys are converted via make.names. This also affects correct specification of gather_cols. This causes problems down the line for filter / dcast etc.

Adapted from package example:

    stocks2 <- data.frame(
        time = as.Date('2009-01-01') + 0:9,
        `X,` = rnorm(10, 0, 1),
        `Y ` = rnorm(10, 0, 2),
        `Z%` = rnorm(10, 0, 4)
    )
    
    gather_(stocks2, "stock", "price", c("X,","Y ","Z%"))  # Error: Unknown column names: X,, Y , Z%
    
    gather(stocks2, stock, price, 2:4)  # works but column names converted to 'X.', 'Y.','Z.' in melted table key column.
    
    # Proving make.names is called somewhere ahead of matching col names:
    gather_(stocks2, "stock", "price", make.names(setdiff(names(stocks2),"time"), unique = TRUE))
    # works (but colnames converted to 'X.','Y.','Z.' in melted table key column)

Can you fix so gather/gather_ accepts illegal column names and doesn't modify them?

**Comment by hadley** [comment]
The problem is `data.frame()`, not gather:

```R
stocks2 <- dplyr::data_frame(
  time = as.Date('2009-01-01') + 0:9,
  `X,` = rnorm(10, 0, 1),
  `Y ` = rnorm(10, 0, 2),
  `Z%` = rnorm(10, 0, 4)
)

gather_(stocks2, "stock", "price", c("X,","Y ","Z%")) 
```

**Comment by markriseley** [comment]
Yup got it, should have spotted that...
