### ISSUE TITLE
NA' by Pivoting Duplicated  OECD-Data - Country-Year-Index

### ISSUE THREAD

**Issue by LuiNov** [hadley/tidyr#1165]
Hey, 

I'm struggling with pivoting from 
**long format:** 
Country | Year (07-20) | Index | Value ) 

**to wide format:** 
( Country | Year | Index_i|..| Index_n) 

It only works of I group by Country and Year but then I would have to bind 13*3 tibbles...
Is there another option ? 

**Heres what I did:** 
###
`# RECODE ------------------------------------------------------------------
OECD0720 %>% select(Land = COU, IND, Jahr = obsTime, Wert = obsValue) %>% 
mutate(across(.cols = c(1,2), ~ as.factor(.x) ) ) %>% mutate(Jahr = as.numeric(Jahr)  )-> OECDI`

**Looks like this ( for 3 Countries Year 07-20 and several INDs):** 

`>  OECDI %>% glimpse
Rows: 1,188
Columns: 4
$ Land <fct> CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, CAN, …
$ IND  <fct> GTR_GDP, GTR_GDP, GTR_GDP, GTR_GDP, GTR_GDP, GTR_GDP, GTR_GDP, GTR_GDP, GTR_GDP, GTR_GDP, GTR_GDP, GTR_GDP, GTR_GDP, GTR_GDP, GTR_POP, GTR_POP, GTR_POP, GTR_POP, GTR…
$ Jahr <dbl> 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 202…
$ Wert <dbl> 41.16, 39.77, 40.40, 39.17, 39.07, 39.20, 39.28, 39.33, 40.77, 41.11, 41.15, 41.93, 42.27, 42.62, 16282.25, 16057.66, 15714.13, 15711.13, 16281.17, 16577.73, 17399.1…
>   `

Then I tried and got NAs (see picture): 
`###
> OECDI %>% pivot_wider(names_from = c(IND), values_from = Wert)
`
![Bildschirmfoto 2021-10-10 um 08 50 44](https://user-images.githubusercontent.com/84698983/136685828-f91cebcd-f07a-457b-952a-047c25f0f868.png)

If I group by Countries I get the same thing so I think the issue is the duplicates in the YEAR-IND pairs. But I dont want single colums for every country, year and IND .... 

Thanks a lot, 
Luise

**Comment by DavisVaughan** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks
