### ISSUE TITLE
FR: apply gather() multiple times at once

### ISSUE THREAD

**Issue by helix123** [hadley/tidyr#119]
Any chance to have an option/syntax to apply `gather()` multiple times at once like described in this SO question with a fake syntax http://stackoverflow.com/questions/32934400/gather-multiple-times-at-once?

I believe datasets like the one described there are common (even with more than two vars to `gather()`) so it would be cool to have an easy syntax for that.

**Comment by hadley** [comment]
Can you please provide a minimal reprex inline?

**Comment by helix123** [comment]
Sure, converted the SO question into a simpler example
Say I have a data.frame dat like this one

``` r
dat <- data.frame(id=c("v1", "v2", "v3"),
                  X_a=c(1,2,3),
                  X_b=c(4,5,6),
                  Y_a=c(7,8,9),
                  Y_b=c(10,11,12))

dat
#>   id X_a X_b Y_a Y_b
#> 1 v1   1   4   7  10
#> 2 v2   2   5   8  11
#> 3 v3   3   6   9  12
```
`dat` shall be gathered to this easily:
``` r
#>   id X_Y_type X Y
#> 1 v1   X_Y_a  1 7
#> 2 v2   X_Y_a  2 8
#> 3 v3   X_Y_a  3 9
#> 3 v1   X_Y_a  4 10
#> 5 v2   X_Y_a  5 11
#> 6 v3   X_Y_a  6 12
````
Some fake syntax could similar to this:
`dat %>%
  gather(X_type = Y_type, list(X, Y), list(X_a:X_b, Y_a:Y_b))`

**Comment by hadley** [comment]
Unfortunately I can't understand what you want here. Where does `X_Y_type` come from? Where does `X_Y_a` come from?  It seems like you want something like this:

```R
data_frame(
  id = c("v1", "v2", "v3"),
  X_a = c(1,2,3),
  X_b = c(4,5,6),
  Y_a = c(7,8,9),
  Y_b = c(10,11,12)
) %>% 
  gather(key, val, X_a:Y_b) %>% 
  separate(key, c("type", "subtype")) %>% 
  spread(type, val)
```

If so, I can't see how you could specify the arguments of gather, separate and spread in one place.

**Comment by helix123** [comment]
Unfortunately, I made a mistake in my previous post (half of the X_Y_a's should be X_Y_b's in the resulting data.frame, edited the post), sorry. But anyway, you found what I was looking for!

I just thought, many people will have data in this format (which feels "well defined" for me) and it would be nice to have a simple command to transform it into "tidy format". Your solution seems to be clearly evident once one goes deeper into tidyr's commands. Maybe it is worthwile to add this example to the package's vignette?

**Comment by wmayner** [comment]
I'd like to request that this be added to the vignettes as well; it's a common and useful pattern, in my experience.
