### ISSUE TITLE
Add '.id' argument to unnest

### ISSUE THREAD

**Issue by cashoes** [hadley/tidyr#125]
When calling unnest on a named list, preserve names as an additional column. The name of the column should be specified by the .id argument.

````
l <- lapply(1:5, function(x) runif(5))
names(l) <- LETTERS[1:5]

df <- data.frame(x = 1:5, y = I(l))

unnest(df, y, .id = 'names')

# Source: local data frame [25 x 3]
# 
#        x names         y
#    (int) (chr)     (dbl)
# 1      1     A 0.6019313
# 2      1     A 0.6589553
# 3      1     A 0.8539686
# 4      1     A 0.3740433
# 5      1     A 0.6602022
# 6      2     B 0.2701723
# 7      2     B 0.7914102
# 8      2     B 0.6098436
# 9      2     B 0.6916693
# 10     2     B 0.3024860
# ..   ...   ...       ...

````

**Comment by hadley** [comment]
This seems like a very reasonable parallel to `dplyr::bind_rows()`.

**Comment by hadley** [comment]
Hmmm, what happens if you're unnesting two named columns?

```R
l <- lapply(1:5, function(x) runif(5))
names(l) <- LETTERS[1:5]

df <- dplyr::data_frame(x = 1:5, x = l, y = l)
unnest(df, x, y, .id = "names")
```

**Comment by lionel-** [comment]
`.id` could be a vector as long as the number of columns to unnest.

**Comment by hadley** [comment]
What if you want to use the names from one, but not another? I guess it could be a named vector, or you could use NAs.

**Comment by lionel-** [comment]
You can also unnest in multiple steps in that case.

**Comment by hadley** [comment]
Currently takes single `.id` string - seems like the job of de-duplication is part of #184 (and if that's not enough, you can always do multiple unnests).
