### ISSUE TITLE
complete() on only a data frame crashes R

### ISSUE THREAD

**Issue by huftis** [hadley/tidyr#126]
The following piece of code consistently crashes R with a ‘caught segfault’ error message.

    library(tidyr)
    d = data.frame(x=1:5)
    complete(d) # Note missing arguments

I have tested this with both the released version of `tidyr` on a Windows 7 system and with the latest Github version of `tidyr` (and `dplyr`).

**Comment by nverno** [comment]
I just noticed this as well.  It seems to be coming from passing a zero length argument for `by` in `dplyr::left_join` which happens if you trace the call above.

Using your `d` this crashes R.
```
## dont run
## dplyr::left_join(data.frame(), d, by=character(0))
```
