### ISSUE TITLE
complete() also changes existing data, not only missing data

### ISSUE THREAD

**Issue by huftis** [hadley/tidyr#127]
The help page for `complete()` makes it look the function can be used to add missing combinations of data, but in fact it also *changes existing data*.

Example code:

    library(tidyr)
    d = data.frame(id=c(1,1,2,2),
                   day=c("mon","tue","tue","wed"),
                   x=c(7,NA,6,5))
    d

This outputs

      id day  x
    1  1 mon  7
    2  1 tue NA
    3  2 tue  6
    4  2 wed  5

Running the `complete()` function on this with `id` and `day` as columns to expand, I would expect a row for ‘id 1, day wed’ and a row ‘id 2, day mon’ to be added, with a custom value of `x`. However, it actually also changes the existing `x` value for ‘id 1, day tue’. That is
  
    complete(d, id, day, fill=list(x=-99))

returns

         id    day     x
      (dbl) (fctr) (dbl)
    1     1    mon     7
    2     1    tue   -99
    3     1    wed   -99
    4     2    mon   -99
    5     2    tue     6
    6     2    wed     5

instead of

         id    day     x
      (dbl) (fctr) (dbl)
    1     1    mon     7
    2     1    tue    NA
    3     1    wed   -99
    4     2    mon   -99
    5     2    tue     6
    6     2    wed     5

Note that the `fill` argument is described in the help file as

> A named list that for each variable supplies a single value to use instead of NA for missing combinations.

However, it’s used for *existing* combinations too, not only missing combinations.

So this is either a bug in the implementation or in the help file. IMHO, the behaviour described in the help file is much more useful than the current behaviour. (When I found this bug, I was using the `complete()` function for some data where the described behaviour of the `fill` argument would be *very* useful, but the actual behaviour wasn’t useful at all.)

**Comment by hadley** [comment]
I think the documentation is technically correct, although it requires a rather close reading. I agree that it would be more useful if only "new" missing values were replaced, but I'm not sure how to implement that yet.
