### ISSUE TITLE
fill not respecting groups?

### ISSUE THREAD

**Issue by derekholmes** [hadley/tidyr#129]
It looks like fill isn't respecting groupings in the following

> df <- data.frame(id="X", Month = 1:3, Year = c(2000, NA,NA))
> dfa <- data.frame(id="Y", Month = 1:3, Year = c(NA,2001,NA))
> group_by(rbind(df,dfa),id) %>% tidyr::fill(Year) %>% as.data.frame()
  id Month Year
1  X     1 2000
2  X     2 2000
3  X     3 2000
4  Y     1 2000 <<< s/b NA
5  Y     2 2001
6  Y     3 2001

>

**Comment by jjcad** [comment]
+1 needs to be fixed. Was pointed here by a comment on my SO thread. http://stackoverflow.com/questions/34517370/group-by-into-fill-not-working-as-expected

**Comment by naveennjs** [comment]
Was this fixed ? I am doing something similar.
df%>%group_by(id,name%>%fill(amount) does not yield the correct results. I am using tidyR version 0.6.1

**Comment by ainhoavega** [comment]
I've spent a full day trying to find a workaround to this problem. Does anyone have any suggestions? Thanks in advance

**Comment by yutannihilation** [comment]
This issue seems fixed. If you feel there's still a same kind of problem, I guess your problem is different, so you should file a new issue with the reproducible example (reprex) for it.

``` r
library(tidyr)
library(dplyr, warn.conflicts = FALSE)

packageVersion("tidyr")
#> [1] '0.8.1'

df <- data.frame(id="X", Month = 1:3, Year = c(2000, NA, NA))
dfa <- data.frame(id="Y", Month = 1:3, Year = c(NA, 2001, NA))
group_by(rbind(df,dfa),id) %>% tidyr::fill(Year) %>% as.data.frame()
#>   id Month Year
#> 1  X     1 2000
#> 2  X     2 2000
#> 3  X     3 2000
#> 4  Y     1   NA
#> 5  Y     2 2001
#> 6  Y     3 2001
```

Created on 2018-08-04 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by ainhoavega** [comment]
The thing is, with a basic df it works, but not with the large df that I have. Could it have something to do with dplyr/plyr/tidyr incompatibilities/bugs?

Sorry for the question, I’m a tidyverse newbie and like I said, I’ve wasted the whole day on this. 

Ainhoa

**Comment by yutannihilation** [comment]
I'm just saying closed GitHub issues are a the good place to ask questions, especially when you can't provide the reprex.

Do you know RStudio Community? I think it's more probable to get the answer there :)

https://community.rstudio.com

**Comment by ainhoavega** [comment]
Thanks, I'll do that. Sorry for the inconvenience.
