### ISSUE TITLE
key,value unclear in spread help file

### ISSUE THREAD

**Issue by jebyrnes** [hadley/tidyr#130]
In working with students, the meaning of key and value in the spread help file is pretty obtuse. After going over it, we've come up with something that might be easier to understand:

key - The bare (unquoted) name of the column whose values will be used as new column headings.

value - The bare (unquoted) name of the column whose values will populate the cells of the resulting data table in the new columns.

Refine as needed, but, something like this when describe keys and values in tidyr will help a lot of folk have an easier time with the spread (and perhaps other) helpfiles.

**Comment by hadley** [comment]
Thanks for the suggestion!
