### ISSUE TITLE
Nesting data frames

### ISSUE THREAD

**Issue by lionel-** [hadley/tidyr#144]
It can be useful to nest data frames so that contextual information is available inside the nests. Here's an  implementation sketch for a `nest_df()` function:

First a C++ util borrowed from purrr to turn a grouped data frame into a list of data frames:
```C++
#include <Rcpp.h>
#include <dplyr.h>
using namespace Rcpp;

// [[Rcpp::export]]
SEXP extract_slices(const List data, const CharacterVector kept_cols) {
  ListOf<IntegerVector> indices(data.attr("indices"));
  int n_slices = indices.size();

  if (n_slices == 0) {
    return data[kept_cols];
  }

  CharacterVector classes = CharacterVector::create("tbl_df", "data.frame");
  dplyr::DataFrameSubsetVisitors visitors(data);

  List out = no_init(n_slices);
  for (int i = 0; i < n_slices; ++i) {
    List out_i = visitors.subset(indices[i], classes);
    out[i] = out_i[kept_cols];
  }

  return out;
}
```

The R functions:
```r
nest_df <- function(data, key, ...) {
  nest_cols <- unname(dplyr::select_vars(names(data), ...))
  nest_df_(data, key, nest_cols)
}

nest_df_ <- function(data, key, nest_cols) {
  group_cols <- setdiff(names(data), nest_cols)

  dfs <- data %>%
    dplyr::group_by_(.dots = group_cols) %>%
    extract_slices(nest_cols)

  out <- data %>%
    dplyr::select_(.dots = group_cols) %>%
    dplyr::distinct()

  out[[key]] <- dfs
  dplyr::tbl_df(out)
}
```

And then:
```r
df <- data_frame(
  a = c(rep(1, 3), rep(2, 3)),
  b = rep(letters[1:3], each = 2),
  c = 1:6,
  d = 6:1
)
df
#> Source: local data frame [6 x 4]
#>
#>       a     b     c     d
#>   (dbl) (chr) (int) (int)
#> 1     1     a     1     6
#> 2     1     a     2     5
#> 3     1     b     3     4
#> 4     2     b     4     3
#> 5     2     c     5     2
#> 6     2     c     6     1

df %>% nest_df("key", c, d)
#> Source: local data frame [4 x 3]
#>
#>       a     b            key
#>   (dbl) (chr)          (chr)
#> 1     1     a <tbl_df [2,2]>
#> 2     1     b <tbl_df [1,2]>
#> 3     2     b <tbl_df [1,2]>
#> 4     2     c <tbl_df [2,2]>
```

**Comment by hadley** [comment]
@lionel- funnily enough I think I'd mostly implemented this locally - have a look at the commits I just pushed.  I've decided to replace the previous `nest()` behaviour because I don't think it's that useful.

**Comment by hadley** [comment]
I'm thinking this is a useful "top-level" data frame: a grouped df has one row per observation; a nested df has one row per group. The nested df is useful when you want to match data to other objects where you have one object per group (e.g. one model per group)

**Comment by lionel-** [comment]
Nice!

The dplyr visitors implementation is slightly faster but nothing dramatic. I think it makes sense to have a `key` argument as in `gather()`. Also the nests should be `tbl_df`. I can send a PR with the visitor implementation some time later if you'd like.


> a grouped df has one row per observation; a nested df has one row per group. 

I wonder if `nest_by()` would be a better interface. Currently we need negative selection to do that. Then we can keep the original `nest()` behaviour (though I agree it isn't that useful). Another idea is `nest_within(x)`, which would detect all variables with the same repetition pattern as `x`. That would be similar to my suggestion in hadley/dplyr#1150

**Comment by hadley** [comment]
@lionel- a PR with those ideas would be great! Thanks!
