### ISSUE TITLE
Remove "into" argument to separate()?

### ISSUE THREAD

**Issue by krlmlr** [hadley/tidyr#148]
When working on #133, I realized that separate() doesn't follow the usual convention, instead there is an "into" argument. The rationale seems to be that ... is used for extra args to strsplit().

I think the following interface would better suit the convention:

```
separate <- function(data, col, ..., sep = separator(), remove = TRUE,
                     convert = FALSE, extra = "warn", fill = "warn")
```

The ... args to strsplit() could be passed using a sentinel:

```
#' @export
separator <- function(sep = "[^[:alnum:]]+", ...) {
  separator_function <- function(value) {
    ...
  }
  structure(separator_function, class = "tidyr_separator")
}

as.tidyr_separator <- ... # UseMethod

as.tidyr_separator.character <- function(x) {
  separator(x)
}
```

@hadley: Would this (slightly breaking) change fit into the upcoming release?

**Comment by hadley** [comment]
Hmmm, it's actually quite breaking as to be consistent you'd do `separate(df, blah, x, y, sep = "|")` instead of `separate(df, blah, c("x", "y"), "|")`. You might be able to detect that case by carefully inspecting the AST, but it would still rely on people always naming the `sep` argument.

**Comment by krlmlr** [comment]
Would you prefer a two-stage process?

1. Introduce sentinel, deprecate the ... argument.
2. Drop "into" argument in favor of a consistent syntax.

**Comment by hadley** [comment]
I'd prefer to leave it as is for now. We can fix syntax inconsistencies in tidyr2 ;)
