### ISSUE TITLE
gather does not respect data.frame options(stringsAsFactors = FALSE) 

### ISSUE THREAD

**Issue by 1beb** [hadley/tidyr#154]
Gather doesn't seem to respect `options(stringsAsFactors = FALSE)`

    str(gather(data.frame(x = 1:5, y = 5:1, z = 5:1)))
     'data.frame':	15 obs. of  2 variables:
         $ key  : Factor w/ 3 levels "x","y","z": 1 1 1 1 1 2 2 2 2 2 ...
         $ value: int  1 2 3 4 5 5 4 3 2 1 ...

One would expect that the key column would be character instead of factor with this option set.

**Comment by hadley** [comment]
I think global options like these are a really bad idea.  But in the dev version of tidyr, gather defaults to using a character column.
