### ISSUE TITLE
nest function doesn't seem to be right?

### ISSUE THREAD

**Issue by happyshows** [hadley/tidyr#160]
> chickwts %>% tbl_df
Source: local data frame [71 x 2]

Hi, 

I was running the code in documentation and it seems the nested data is off by one row.

   weight      feed
    (dbl)    (fctr)
1     179 horsebean
2     160 horsebean
3     136 horsebean
4     227 horsebean
5     217 horsebean
6     168 horsebean
7     108 horsebean
8     124 horsebean
9     143 horsebean
10    140 horsebean
..    ...       ...
> chickwts %>% nest(weight)
       feed                                                                 data
1 horsebean           368, 390, 379, 260, 404, 318, 352, 359, 216, 222, 283, 332
2   linseed                     179, 160, 136, 227, 217, 168, 108, 124, 143, 140
3   soybean           309, 229, 181, 141, 260, 203, 148, 169, 213, 257, 244, 271
4 sunflower                325, 257, 303, 315, 380, 153, 263, 242, 206, 344, 258
5  meatmeal 243, 230, 248, 327, 329, 250, 193, 271, 316, 267, 199, 171, 158, 248
6    casein           423, 340, 392, 339, 341, 226, 320, 295, 334, 322, 297, 318

**Comment by happyshows** [comment]
sessionInfo()
[1] dplyr_0.4.3.9000 tidyr_0.4.0.9000

**Comment by ginolhac** [comment]
I agree that the nesting seems not be right. Following the [blog post](http://blog.rstudio.org/2016/02/02/tidyr-0-4-0/)

```gapminder::gapminder%>%
  dplyr::filter(continent == "Asia", country == "Afghanistan")
Source: local data frame [12 x 6]

       country continent  year lifeExp      pop gdpPercap
        (fctr)    (fctr) (int)   (dbl)    (int)     (dbl)
1  Afghanistan      Asia  1952  28.801  8425333  779.4453
2  Afghanistan      Asia  1957  30.332  9240934  820.8530
3  Afghanistan      Asia  1962  31.997 10267083  853.1007
4  Afghanistan      Asia  1967  34.020 11537966  836.1971
```

While, `nest()` gives other values

```
by_country <- gapminder::gapminder %>% 
    group_by(continent, country) %>% 
    nest()
by_country[1, ] # check Asia + Afghanistan
Source: local data frame [1 x 3]

  continent     country            data
     (fctr)      (fctr)           (chr)
1      Asia Afghanistan <tbl_df [12,4]>
# unnest for this row
by_country[1,]$data[[1]]
Source: local data frame [12 x 4]

    year lifeExp      pop gdpPercap
   (int)   (dbl)    (int)     (dbl)
1   1952  43.077  9279525  2449.008
2   1957  45.685 10270856  3013.976
3   1962  48.303 11000948  2550.817
4   1967  51.407 12760499  3246.992
```

Actually, data come from `Africa, Algeria` seems like the data are arrange per `continent`, while grouped columns are arranged by `country`.


tidyr 0.4.0
dplyr 0.4.3

**Comment by hadley** [comment]
Could you please provide a minimal reproducible example that I can easily copy and paste into R?

**Comment by happyshows** [comment]
works now, thanks.

**Comment by ginolhac** [comment]
perfect, thanks a lot
