### ISSUE TITLE
Nesting and data-frame columns

### ISSUE THREAD

**Issue by jeroenooms** [hadley/tidyr#162]
The term *nested* is a bit ambiguous as it can refer both to a dataframe column and a list of dataframes. In tidyr you exclusively treat the latter, but dataframe columns are common in json data. It would be nice if these structures can be tidy'd as well.

Example from the jsonlite [paper](http://arxiv.org/pdf/1403.2805v1.pdf) (section 2.4.4 and 2.4.5):

```r
options(stringsAsFactors=FALSE)
x <- data.frame(driver = c("Bowser", "Peach"), occupation = c("Koopa", "Princess"))
x$vehicle <- data.frame(model = c("Piranha Prowler", "Royal Racer"))
x$vehicle$stats <- data.frame(speed = c(55, 34), weight = c(67, 24), drift = c(35, 32))
str(x)
```
```
'data.frame':	2 obs. of  3 variables:
 $ driver    : chr  "Bowser" "Peach"
 $ occupation: chr  "Koopa" "Princess"
 $ vehicle   :'data.frame':	2 obs. of  2 variables:
  ..$ model: chr  "Piranha Prowler" "Royal Racer"
  ..$ stats:'data.frame':	2 obs. of  3 variables:
  .. ..$ speed : num  55 34
  .. ..$ weight: num  67 24
  .. ..$ drift : num  35 32
```

The json representation of this structure:

```r
toJSON(x, pretty = TRUE)
```
```
[
  {
    "driver": "Bowser",
    "occupation": "Koopa",
    "vehicle": {
      "model": "Piranha Prowler",
      "stats": {
        "speed": 55,
        "weight": 67,
        "drift": 35
      }
    }
  },
  {
    "driver": "Peach",
    "occupation": "Princess",
    "vehicle": {
      "model": "Royal Racer",
      "stats": {
        "speed": 34,
        "weight": 24,
        "drift": 32
      }
    }
  }
] 
```

**Comment by hadley** [comment]
The thing I don't like about this is that it seems to violate the usual constraints of a data frame - each element of a data frame must be the same length, and the length of a data frame is the number of columns, not number of rows.

**Comment by hadley** [comment]
I'd probably be willing to review a PR that implemented everything that this needed to work, but I'm generally pessimistic because it requires treating lists in two different ways depending on whether or not they inherit from data frame. 

In other words, I really dislike this:

```R
> NROW(list(x = 1:5))
[1] 1
> NROW(data.frame(x = 1:5))
[1] 5
```
