### ISSUE TITLE
unnest() function

### ISSUE THREAD

**Issue by dabsingh** [hadley/tidyr#164]
Hello Folks.. Greetings.

I'm using tidyr_0.4.1 and dplyr_0.4.3.

Here is a snippet of code that makes use of unnest function. I split column "a" and unnest it later but in this process the column "b" is completely wiped out. I'm I missing something?

`library(dplyr)`
`library(tidyr)`
`df <- data_frame(a=c("A1-A2-A3-A4", ""), b=c("", "B1"))`
`df %>% dplyr::mutate(a=strsplit(a, "-")) %>% unnest(a)`

Attached the result.

![image](https://cloud.githubusercontent.com/assets/1531502/12966563/5075e984-d014-11e5-9f5c-5729ed20dd11.png)

**Comment by hadley** [comment]
That seems to be as expected:

```R
df %>% dplyr::mutate(a=strsplit(a, "-"))
#> Source: local data frame [2 x 2]
#> 
#>          a     b
#>      (chr) (chr)
#> 1 <chr[4]>      
#> 2 <chr[0]>    B1
```

i.e. there are 0 values of a that correspond to "b1"
