### ISSUE TITLE
complete() on grouped data_frame throws unhelpful error message

### ISSUE THREAD

**Issue by sfirke** [hadley/tidyr#167]
This works:

```
mtcars %>%
  slice(1:5) %>%
  complete(am, cyl, fill = list(mpg = NA, gear = 10))
```

But if you are coming from a dplyr pipeline that results in a grouped data_frame, like this:

```
mtcars %>%
  slice(1:5) %>%
  group_by(vs) %>%
  complete(am, cyl, fill = list(mpg = NA, gear = 10))
```

You get:

> Error in left_join_impl(x, y, by$x, by$y) : 
>   attempt to set index 7/7 in SET_STRING_ELT

I'd expect `complete()` to ungroup the data_frame before running, as `complete()` has its own grouping variables (**edit**: maybe I'm unsophisticated as I see a post like this http://stackoverflow.com/questions/32973050/using-tidyrcomplete-with-group-by where the user is looking for that functionality).  But in the case that this *should* cause an error as it does, a clearer error message like "Error: attempting to call complete() on a grouped data_frame" would aid users in debugging.

**Comment by hadley** [comment]
This now does the right thing in the dev version.
