### ISSUE TITLE
gather observations from multiple sets of columns of different types without degrading them to character

### ISSUE THREAD

**Issue by lucasmation** [hadley/tidyr#174]
described in more detail in [this SO question](http://stackoverflow.com/questions/36133017/tidyrgather-observations-from-multiple-sets-of-columns-of-different-types?noredirect=1#comment59905551_36133017). 

The tidyr solution suggested by Hadley in one of the SO questions involves gather to a "ultra_long" format then spread to "long" format (example bellow). But this degrades all variable types to string.

I love coding in Hadleyverse style. It is very annoying that there is no better way to do this in tidyr. 

```
#Answer using: Dplyr + tidyr
d_wide %>% 
  gather(variable, value, -pair_id) %>% 
  separate(variable, into = c("var", "status"),       ## Split "variable" column into two...
           sep = "(?<=name|blood_type|age)", perl = TRUE) %>% 
  mutate(status=substr(status,2,5)) %>%
  spread(var, value, convert = TRUE) %>% str()

# Simpler sintax, but does not preserve variable types


#resposta usando o data.table::melt
melt(data=as.data.table(d_wide),
     measure = patterns("name","blood_type","age"),
     value.name = c("name","blood_type","age"))[
       , variable := factor(variable, labels = c('wife','husb'))][] %>% str()

# Preserves variable types
```

**Comment by jennybc** [comment]
I'm pretty sure you are underscoring the importance of careful type conversion in multi-gather, which is #150.

**Comment by lucasmation** [comment]
Correct. Good catch @jennybc . I hope they release this soon. Tks.
