### ISSUE TITLE
Nesting argument not working with expand() and complete() 

### ISSUE THREAD

**Issue by eliasdabbas** [hadley/tidyr#178]
```
> cars <- data.frame(make = c('toyota', 'toyota', 'honda'), 
+                    model = c('camry', 'corola', 'civic'),
+                    year = c(2014, 2015, 2015))
> cars %>% expand(nesting(make, model), year)

Error: No variables selected
```
Same error showing up with the examples in the documentation. 

RStudio: 0.99.1115
tidyr: 0.4.1.9000 and 0.4.1
Mac OSX El Capitan

**Comment by eliasdabbas** [comment]
Issue resolved when I downgraded dplyr to 0.4.3 from the dev version. Nesting seems to work fine now.

**Comment by mdsumner** [comment]
Here's my report fwiw: https://gist.github.com/mdsumner/13ebc4240fba6aedd9a2186ec476ca25

Thanks for the heads up on dplyr dev.

**Comment by masalmon** [comment]
Just for referencing these related issues https://github.com/hadley/dplyr/issues/1746 and https://github.com/hadley/dplyr/issues/1751
