### ISSUE TITLE
Ability to use tidyr within dplyr without explicit variable creation

### ISSUE THREAD

**Issue by derekholmes** [hadley/tidyr#191]
It would be nice for e.g. unite to work without an explicit variable being created, i.e.
`> data_frame(aa=c("A","B","C"),bb=1:3,cc=10:12) %>% filter(tidyr::unite(aa,bb)=="B_2")`
gives
Error: Invalid column specification
but
` data_frame(aa=c("A","B","C"),bb=1:3,cc=10:12) %>% unite(xx,aa,bb) %>% filter(xx=="B_2")`
works.

**Comment by hadley** [comment]
The point of all tidyr functions is to create modified data frames. Maybe you just want paste?

```R
data_frame(aa=c("A","B","C"),bb=1:3,cc=10:12) %>% filter(paste(aa,bb,sep = "_")=="B_2")
```

Although really I'd think that this would be better:

```R
data_frame(aa=c("A","B","C"),bb=1:3,cc=10:12) %>% filter(aa = "B", b == 2)
```
