### ISSUE TITLE
extract_numeric returns positive on negative numbers

### ISSUE THREAD

**Issue by barryrowlingson** [hadley/tidyr#20]
extract_numeric("-123") returns 123, because all it does is strip anything not 0-9 or decimal point.

Its documentation is pretty thin too.

discussion here:
http://stackoverflow.com/questions/25291191/can-extract-numeric-deal-with-negative-numbers

**Comment by gabx** [comment]
> extract_numeric("23 ft-lbs")
[1] NA
   Warning message:
   In extract_numeric("23 ft-lbs") : NAs introduced by coercion
The minus sign in the regex is maybe good for "-123" but leads to errors too.
