### ISSUE TITLE
as_data_frame_matrix: "envir" argument in getS3method

### ISSUE THREAD

**Issue by itsdalmo** [hadley/tidyr#202]
It seems like `envir` is not a valid argument in `utils::getS3method` in R version 3.2.4. Couldn't find a specific mention of when this was added to `R.utils`, but unless there is something wrong with my R install I suppose this warrants a version bump for the R in `DESCRIPTION`. 

`getS3method` is only used on one line however, so it might be a better idea to just add an `if` statement for older versions of R (where envir is not an argument) and something like this:

```R
get("as_data_frame.matrix", envir = asNamespace("tibble"))
```

Could submit a PR if I have the right idea here (and figure out which version of `R.utils` added the argument).

-Kristian

**Comment by hadley** [comment]
Probably @krlmlr should at least take a look at this because he did the original PR.

I just submitted tidyr to CRAN so we'll probably need a fix soon.

**Comment by krlmlr** [comment]
It's been introduced in R 3.3.0 (https://github.com/wch/r-source/commit/9d226b4940246d12#diff-a76a25f7e4bd0d72aded7945249a3a5aR255). I'll submit a compatibility fix.
