### ISSUE TITLE
unnest list column like a numeric column

### ISSUE THREAD

**Issue by kendonB** [hadley/tidyr#207]
I'd like to be able to nest a ``data.frame``, perform an operation that creates a data.frame (i.e. 1 per nest element), then unnest so that this data.frame is repeated in the original df, much like the unnest operation for ``numeric`` columns.

```
make_df <- function(x){
  data.frame(one = 1)
}
iris %>% group_by(Species) %>% 
  nest() %>% 
  mutate(df_col = data %>% map(make_df)) %>% 
  # Now there is a column of single data.frames as well as data
  # I'd like this to unnest like a numeric column.
  unnest()
# Error: All nested columns must have the same number of elements.
```

**Comment by hadley** [comment]
I think what you're asking for is for `unnest()` to recycle singe-row data frames in the same way it recycles vectors.  I think that's a reasonable request.

**Comment by kendonB** [comment]
No, I was after arbitrary rows ``data.frames`` that are all the same length, though they wouldn't need to be.

The real-life application is a set of 28 rasters which have 15 unique resolutions and I'm (expensively) computing the cell area overlaps with a ``SpatialPolygonsDataFrame``.

- First df has a row for each raster (nrow=28)
- Nested df has a row for each unique raster resolution type (nrow=15)
- Output for each of these 15 is a ``data.frame`` with two columns (the raster cell id and the overlap area) (nrow=60)

I'd like to be able to then get the 28 row df back, with the output data.frame repeated within each unique raster resolution.

Thanks so much!

**Comment by kendonB** [comment]
This is a hack for anyone interested for now:

```
make_df <- function(x){
  data.frame(rand_len = rep(1, sample(1:10, size = 1)))
}
iris_tmp <- iris %>% group_by(Species) %>% 
  nest() %>% 
  mutate(df_col = data %>% map(make_df)) 
iris_final <- left_join(as.tbl(iris), iris_tmp) 

```

**Comment by kendonB** [comment]
This seems to work by using ``.drop = FALSE`` and naming the list you wish to unnest.

```
iris %>% group_by(Species) %>% 
  nest() %>% 
  mutate(df_col = data %>% map(make_df)) %>% 
  # Now there is a column of single data.frames as well as data
  # I'd like this to unnest like a numeric column.
  unnest(data, .drop = FALSE)
```
