### ISSUE TITLE
documentation: expand and factors

### ISSUE THREAD

**Issue by Aljk** [hadley/tidyr#212]
I noticed that  `expand(df, id, time)` creates a row not for every combination of `df$id `and `df$time`, but if `df$id` is a factor for every combination of `levels(df$id)` and `df$time`. 

In many situations this is somewhat counter-intuitive and should maybe be mentioned in the documentation. `droplevels()` quickly solves the problem, but nevertheless in my case it caused some confusion and led to false results. So I think it would really help users if this particularity was mentioned in the documentation.

**Comment by hadley** [comment]
I think this is sort of implicit in the definition - `expand()` is designed to create combinations that don't exist in the data. But I've added a note about factor to try and make it more clear.
