### ISSUE TITLE
Provide rbind solution that can add list element names as a variable in the output

### ISSUE THREAD

**Issue by jennybc** [hadley/tidyr#22]
Problem: you have a list of data.frames and the element names convey information. You want to row bind them together and, in the new data.frame, you want a variable for the list element each observation originated in.

![2014-08-22_rbind-and-store-as var](https://cloud.githubusercontent.com/assets/599454/4014866/0ed7df14-2a25-11e4-9a31-b086f3cc37b9.png)

Demo: fragment subset of iris into separate data.frames, stored as list.
Note: Species info carried _only_ via list names

``` r
my_list <- lapply(split(subset(iris, select = -Species),
                        iris$Species), "[", 1:2, )
```

Simple rbind-y calls cannot recover Species:

``` r
do.call("rbind", my_list) # rownames have never looked so good ...
```

```
##               Sepal.Length Sepal.Width Petal.Length Petal.Width
## setosa.1               5.1         3.5          1.4         0.2
## setosa.2               4.9         3.0          1.4         0.2
## versicolor.51          7.0         3.2          4.7         1.4
## versicolor.52          6.4         3.2          4.5         1.5
## virginica.101          6.3         3.3          6.0         2.5
## virginica.102          5.8         2.7          5.1         1.9
```

``` r
dplyr::rbind_all(my_list)
```

```
##   Sepal.Length Sepal.Width Petal.Length Petal.Width
## 1          5.1         3.5          1.4         0.2
## 2          4.9         3.0          1.4         0.2
## 3          7.0         3.2          4.7         1.4
## 4          6.4         3.2          4.5         1.5
## 5          6.3         3.3          6.0         2.5
## 6          5.8         2.7          5.1         1.9
```

Current workaround: prep with mapply() to restore Species, then rbind (thanks @kara_woo for this snippet)

``` r
my_list2 <-
  mapply(`[<-`, my_list, 'Species', value = names(my_list), SIMPLIFY = FALSE)
dplyr::rbind_all(my_list2)
```

```
##   Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
## 1          5.1         3.5          1.4         0.2     setosa
## 2          4.9         3.0          1.4         0.2     setosa
## 3          7.0         3.2          4.7         1.4 versicolor
## 4          6.4         3.2          4.5         1.5 versicolor
## 5          6.3         3.3          6.0         2.5  virginica
## 6          5.8         2.7          5.1         1.9  virginica
```

**Comment by hadley** [comment]
FWIW, I've removed this experimental method because I'm now pretty sure it's a bad idea (and `dplyr::bind_rows()` should do the equivalent in the next version)

**Comment by hadley** [comment]
Hmmm, but maybe `unnest()` needs to handle the case where a column of the data frame is a list of data frames:

```R
data_frame(
  x = c(1, 2),
  y = c(3, 4),
  z = list(data_frame(a = 1), data_frame(a = 1:3))
)
```

(and those data frames could contain lists-columns themselves, but I think you'd need a second unnest to handle that)

I'm not certain whether or not this is useful (it might crop up as an alternative way of handling relational data), but it is interesting.

**Comment by hadley** [comment]
Oh that's #58

**Comment by dlebauer** [comment]
So ... in case anyone else finds this in their search for adding a new column with `bind_rows` (or `rbind_list` or `do.call(rbind, ...)` and return a new column without inelegant convulsions... I'll finish out the example to demonstrate:

By 

> `dplyr::bind_rows()` should do the equivalent in the next version

What I gather is that (using dplyr 0.5.0) the argument `.id` can be used to specify the new column name, so following from the example https://github.com/tidyverse/tidyr/issues/22#issue-40933107

```r
bind_rows(my_list, .id = 'species')
```

returns 

```
     species Sepal.Length Sepal.Width Petal.Length Petal.Width
1     setosa          5.1         3.5          1.4         0.2
2     setosa          4.9         3.0          1.4         0.2
3 versicolor          7.0         3.2          4.7         1.4
4 versicolor          6.4         3.2          4.5         1.5
5  virginica          6.3         3.3          6.0         2.5
6  virginica          5.8         2.7          5.1         1.9
```

P.S. thanks again for all of the great work you and your team are doing!

**Comment by d8aninja** [comment]
Is there a solution for the cases when `rbind_rows` will not accomplish this task if the constituent lists are of different length?  In these cases I usually appeal to `do.call(rbind, df)` but there is obviously no `.id` argument to go along with that solution...

**Comment by jennybc** [comment]
@d8aninja Do you want to make a little example that shows exactly what you mean (I'm not entirely sure) and ask it over in the [tidyverse section of community.rstudio.com](https://community.rstudio.com/c/tidyverse)? This question is a good fit.

**Comment by d8aninja** [comment]
@jennybc will do, thanks!

**Comment by dwinsemius** [comment]
> On Sep 28, 2017, at 10:14 AM, Jeff <notifications@github.com> wrote:
> 
> Is there a solution for the cases when rbind_rows will not accomplish this task if the constituent lists are of different length? In these cases I usually appeal to do.call(rbind, df) but there is obviously no .id argument to go along with that solution...
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


The dplyr package has a `bind_rows` function. Missing items are filled with NA.

Also see: rbind.fill in plyr-pkg. 

-- 


David Winsemius
Alameda, CA, USA

'Any technology distinguishable from magic is insufficiently advanced.'   -Gehm's Corollary to Clarke's Third Law

**Comment by agilebean** [comment]
> Thank -- yes `unnest()` does it!

@jennybc can you show in code how this works?

I tried this with throws an error:
```
> my_list %>% unnest
Error in UseMethod("unnest_") : 
  no applicable method for 'unnest_' applied to an object of class "list"
```

**Comment by poidstotal** [comment]
The built in method that works for me was to loop through the list and add the item name as a constant column.
```
for (i in 1:length(mylist)) {
  mylist[[i]]$year <- as.numeric(names(mylist[i]))
}
```
