### ISSUE TITLE
Extract and ignore case in regex

### ISSUE THREAD

**Issue by tatapoum** [hadley/tidyr#223]
I try to use the extract function with the ignore.case parameter (from regexec).

```
input <- data.frame(full_address = "Domaine de la Motte au Vicomte BP 35327")

ok <- extract(input, full_address, c("address", "pb"), regex = "(.+?)(BP \\d+)", remove = FALSE)
ko <- extract(input, full_address, c("address", "pb"), regex = "(.+?)(bp \\d+)", remove = FALSE, ignore.case = TRUE)

```

**Comment by hadley** [comment]
`extract()` doesn't use `regexec()` so this parameter is not currently supported

**Comment by kleinschmidt** [comment]
The docs for `extract` says that additional arguments are passed to `regexec`, which is quite misleading: https://github.com/tidyverse/tidyr/blob/master/R/extract.R#L38
