### ISSUE TITLE
Expand function

### ISSUE THREAD

**Issue by matthieugomez** [hadley/tidyr#30]
Expand function, as proposed in #21 would be very useful, especially if it works with `group_by`. For instance on a grouped data.table:

````R
expand_.grouped_dt <- function(.data,...,.dots){
  dots <- lazyeval::all_dots(.dots, ...)
  var_name <- names(dplyr::select_vars_(names(.data), dots))
  byvars <- dt_env(.data, lazyeval::common_env(dots))$vars
  for (t in var_name) {
    setkeyv(.data,c(byvars, t))
    call <- substitute(.data[, list(seq.int(t[1], t[.N])), by = c(byvars)], list(t = as.name(t)))
    ans  <- eval(call)
    setnames(ans, c(byvars, t))
    setkeyv(ans, c(byvars, t))
    .data <- .data[ans, allow.cartesian = TRUE]
  }
  .data
}
````

Related stackoverflow questions: 
http://stackoverflow.com/questions/25694940/from-unbalanced-to-balanced-panel
http://stackoverflow.com/questions/16878905/data-table-outer-join-by-group
http://stackoverflow.com/questions/10438969/fastest-way-to-add-rows-for-missing-values-in-a-data-frame
http://stackoverflow.com/questions/22956803/fastest-way-for-filling-in-missing-dates-for-data-table

**Comment by hadley** [comment]
Now part of #81
