### ISSUE TITLE
spread with code and description key

### ISSUE THREAD

**Issue by matthieugomez** [hadley/tidyr#40]
In a lot of cases, a "long" dataset format has actually two columns for keys: a code, and a description. When "spreading it", the code column does not make a lot of sense without the description column (and the description column may be too long for variable names). 

````R
library(dplyr)
df <- data.frame(
  id     = c(1, 1),
  variable     = c("ind331", "ind33"),
  description  = c("Primary metals manufacturing", "Fabricated metal product"),
  value        = c(93,14)
)
df %>% select(-description) %>% spread(variable, value)
````

That would be nice if there was a good way to deal with this case (maybe by adding a label attribute to the data.frame output by `spread`)

Example : http://www.bea.gov/regional/downloadzip.cfm

**Comment by hadley** [comment]
I think this is a general case of having a data frame that contains two "types" of data, and it should be solved with better tools like #14, rather than add more behaviour to `spread()`.
