### ISSUE TITLE
case for changing argument order in gather()

### ISSUE THREAD

**Issue by Mullefa** [hadley/tidyr#53]
I'd like to make a case for changing the order of the arguments in `gather()` to this:

```R
gather(data, ..., key = "key", value = "value", na.rm = FALSE, convert = FALSE)
```

This means that when using the pipe operator `%>%` with `spread()` or `gather()` it will always read:

```
data => verb => columns to 'operate' + some other stuff
```

**Comment by hadley** [comment]
Regardless of the merits, it's too late to make this change as it would break existing code.
