### ISSUE TITLE
tidy-data.Rmd: Section links don't work on CRAN

### ISSUE THREAD

**Issue by seaaan** [hadley/tidyr#55]
Section references appear in tidy-data.Rmd, but rather than appearing as links/linkable objects, the markdown appears. For example, on CRAN, the title of one section appears like this: "# Defining tidy data {#sec:defining}" 

This occurs on code lines 20, 93, end of 131, and 237.

I don't know how to fix this, so I'm reporting it as an issue.

**Comment by hadley** [comment]
Closed in 63d4834683346d6795b2294ab237faa2c489d4e0
