### ISSUE TITLE
Implement renaming of columns in gather()

### ISSUE THREAD

**Issue by rmatev** [hadley/tidyr#60]
While `gather()` uses `select_vars()` underneath, it ignores variable renaming. It would be nice if `gather_()` can accept a named vector for `gather_cols` and rename the values in the `key` column.

The desired output using the example from `?gather` is:
```
gather(stocks, stock, price, -time, XNEW=X)
#          time stock       price
# 1  2009-01-01     XNEW -0.94386401
# 2  2009-01-02     XNEW -0.36005819
# 3  2009-01-03     XNEW  0.22049081
# 4  2009-01-04     XNEW  0.45765251
# ...
```

**Comment by hadley** [comment]
You'd probably write that as

```R
gather(stocks, stock, price, XNEW = X, Y, Z)
```

That seems like a reasonable feature.

**Comment by hadley** [comment]
I've changed my mind again - I think I'd now prefer `gather()` to one thing well, so renaming can happen in `rename()`.
