### ISSUE TITLE
Suggested update to extract_numeric

### ISSUE THREAD

**Issue by mikaelmoutakis** [hadley/tidyr#64]
```
#This update fixes three problems
#1. When "," or anything else is used as decimal point
#2. Some word processors unhelpfully converts the standard
# hyphen-minus sign
# to a en-dash sign –, a minus sign or a 
# full-width hyphen-minus sign －. 
#3. When . or another sign is used as a thousand separator
#https://en.wikipedia.org/wiki/Plus_and_minus_signs#Minus_sign
#https://en.wikipedia.org/wiki/Decimal_mark
#http://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html

extract_numeric <- function(x,dec=".",thousand.sep="") {
  x <- sub("(–|−|－)","-",as.character(x))
  if(dec!="."){
    if(thousand.sep=="."){
      x <- gsub("[.]","",x)
    }
    x <- sub(dec,".",x)
  }
  as.numeric(gsub("[^0-9.-]+", "", x))
}

txt <- c("–33","1 088,3","−22,4","- 1 000 ,333","－23.2")
extract_numeric(txt,dec=",")

txt2 <- c("1,888,348.3","1,888,348 .99")
extract_numeric(txt2)

txt3 <- c("8.333'9")
extract_numeric(txt3,dec="'",thousand.sep=".")

txt4 <- c("4.294.967.295,000")
extract_numeric(txt4,dec=",",thousand.sep=".")


```

**Comment by mikaelmoutakis** [comment]
Also, according to wikipedia some countries like Spain use a dot as a thousand separator. This would complicate the matter, I think. 

https://en.wikipedia.org/wiki/Decimal_mark
http://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html

**Comment by mikaelmoutakis** [comment]
If you like the suggested change, I can write up a series of tests.

**Comment by hadley** [comment]
I'd rather rethink the design of `extract_numeric` altogether. I think it might be better to think about extracting the longest sequence of numeric + punctuation characters, turning that into a number, and then looking for a negative indicator.

**Comment by mikaelmoutakis** [comment]
As long as there is a way to define the decimal character. Otherwise extract_numeric is only useful for US/UK

**Comment by hadley** [comment]
FWIW, I might actually deprecrate this function in favour of `readr::parse_numeric()`
