### ISSUE TITLE
Gather may have problems with POSIX data types

### ISSUE THREAD

**Issue by simonthelwall** [hadley/tidyr#73]
The following causes R to crash with a segfault. 
```
DF <- structure(list(Time = structure(1:5, .Label = c( '2015-03-10T11:25:35Z','2015-03-10T11:25:40Z','2015-03-10T11:25:41Z','2015-03-10T11:25:42Z','2015-03-10T11:25:43Z'), class = "factor"), 
   Bid = c(6118.5, 6118.5, 6119.5, 6119, 6119), 
   Offer= c(6119.5, 6119.5, 6119.5, 6120, 6119.5)), 
  .Names = c("Time", "Bid", "Offer"), row.names = c(NA, -5L), class = "data.frame")

DF$Time <- strptime(DF$Time, format = "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")

df2 <- gather(DF, type, value, -Time)
head(df2)
```
However, the next snippet runs fine. 

````
test <- data.frame(time = strptime(c("2006-01-08 10:07:52", "2006-08-07 19:33:02"),
              "%Y-%m-%d %H:%M:%S", tz = "EST5EDT"),
              x = c(1, 2), y = c(3,4))
test

test2 <- gather(test, y, val, -time)
test2
```

```
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tidyr_0.2.0

loaded via a namespace (and not attached):
[1] tools_3.1.2
```

**Comment by dwinsemius** [comment]
Segfaults on my 3.1.2 (SL branch) with tidyr 0.2.0 on a machine with OSX 10.7.5

**Comment by hadley** [comment]
@kevinushey do you have some time to look into this? `gather()` is a thin wrapper around `reshape2::melt()`.  (I'm also thinking about copying `melt_dataframe()` into tidyr so I can get rid of the reshape2 dependency altogether)

**Comment by dwinsemius** [comment]
Still segfaults after updating to  3.2.1 (SL branch) still with tidyr 0.2.0  and reshape2 1.4.1 on a machine with OSX 10.7.5 which explains why need to be running the SL branch.

**Comment by hadley** [comment]
@dwinsemius no need to tell us again that it's a problem

**Comment by hadley** [comment]
The problem is that `strptime()` creates a POSIXlt, but you almost always want a POSIXct.

@kevinushey maybe you never tested the implementation of `REP(VECSXP)`. I don't understand the code enough to know why you thought `DO_REP(VECSXP, SEXP, STRING_PTR)` would work :wink:

**Comment by kevinushey** [comment]
`STRING_PTR` is defined like this:

```
#define STRING_PTR(x)	((SEXP *) DATAPTR(x))
```

So it does the 'right' thing for `VECSXP`s as well. Technically, it does the same thing as `VECTOR_PTR` but we're not allowed to use that unless `#define USE_RINTERNALS` is present.

The `REP(VECSXP)` branch is to enable recycling of `data.frame`s with `list` components; apparently something else is missing?

**Comment by kevinushey** [comment]
Also, we should definitely keep the `melt` code in one place. Is there any reason why we can't just have `tidyr` depend on `reshape2` and get `melt` from there?

**Comment by kevinushey** [comment]
`reshape2` has this test:

```
test_that("melt.data.frame allows for lists in the set of id variables", {
  df <- data.frame(x = 1:5)
  df$y <- list(
    data.frame(),
    new.env(),
    as.name("foo"),
    1,
    as.POSIXct(Sys.Date())
  )
  df$za <- letters[1:5]
  df$zb <- letters[6:10]
  df$zc <- letters[11:15]
  result <- melt(df, id=1:2)
  expect_identical(result$y[1:5], df$y)
})
```

so I think something else may be going on?

**Comment by kevinushey** [comment]
I'm guessing the error is really due to malformed `POSIXlt` objects created by `melt`; we probably need to do something special to copy the attributes properly.

Ie, after `melt`ing, the `POSIXlt` object looks like this:

```
> attributes(melted$Time)
$class
[1] "POSIXlt" "POSIXt"

$tzone
[1] "UTC"
```

The `names` attribute is now missing; that needs to be explicitly copied for `POSIXlt` objects.

**Comment by kevinushey** [comment]
Basically `melt` just doesn't understand how to repeat `POSIXlt` objects; we could probably just fall back to the base R `rep` for those cases. But this is downright _weird_ to me:

```R
> tm <- as.POSIXlt(Sys.time())
> unclass(tm)
$sec
[1] 25.83561

$min
[1] 52

$hour
[1] 10

$mday
[1] 24

$mon
[1] 7

$year
[1] 115

$wday
[1] 1

$yday
[1] 235

$isdst
[1] 1

$zone
[1] "PDT"

$gmtoff
[1] -25200

attr(,"tzone")
[1] ""    "PST" "PDT"
> unclass(rep(tm, 3))
$sec
[1] 25.83561 25.83561 25.83561

$min
[1] 52 52 52

$hour
[1] 10 10 10

$mday
[1] 24 24 24

$mon
[1] 7 7 7

$year
[1] 115 115 115

$wday
[1] 1 1 1

$yday
[1] 235 235 235

$isdst
[1] 1 1 1

$zone
[1] "PDT" "PDT" "PDT"

$gmtoff
[1] -25200 -25200 -25200

attr(,"tzone")
[1] ""    "PST" "PDT"
```

So `rep`ing a `POSIXlt` means `rep`ing each sub-element within; in other words, a `POSIXlt` is not a self-contained object, even its internal representation is vectorized. That's really darn weird, right?

**Comment by kevinushey** [comment]
PR: https://github.com/hadley/reshape/pull/69

**Comment by hadley** [comment]
I think POSIXlt objects are fundamentally a mistake - in S3, you really can't override the `names()` and `length()` accessor and expect things to work reliably :/

I'd want to break the tight tidyr-reshape2 connection because:

1. Currently reshape2 (and hence tidyr) breaks if you load reshape
1. Reshape2 depends on plyr, and I'm trying to slowly remove that dependency everywhere
1. `melt` and `gather` are slightly different so I think the gather C code might evolve in a slightly different direction over time

It would be possible to fix these issues by doing more work on reshape2, but I'm trying to avoid that so I can focus my development efforts on as few packages as possible.
