### ISSUE TITLE
keep rows in expand

### ISSUE THREAD

**Issue by blasern** [hadley/tidyr#82]
Could we have a `keep` argument in `expand`, such that some columns can be kept, but not expanded? It's basically like `expand` and then `left_join`, but works better in chains. 
[Related SO question](http://stackoverflow.com/questions/30356884/adding-default-values-to-item-x-group-pairs-that-dont-have-a-value-df-spre/30370700#30370700)

    expand <- function(data, ..., keep = NULL) {
      dots <- lazyeval::lazy_dots(...)
      expand_(data, dots, keep = keep)
    }
    
    expand_.data.frame <- function(data, dots, ..., keep = keep) {
      dots <- lazyeval::as.lazy_dots(dots)
      if (length(dots) == 0)
        return(data.frame())
      
      pieces <- lapply(dots, unique_vals, data = data)
      
      res <- Reduce(cross_df, pieces)
      
      if (length(keep) > 0){
        keep <- data[, unique(c(names(res), keep))]
        res <- dplyr::left_join(res, as.data.frame(keep), by = names(res))
      }
      
      res
    }
    
    df <- data.frame(groupid = c(1:2, 1),
                     itemid = c(1:2, 2),
                     itemname = c("a", "b", "b"),
                     value = 1:3,
                     value2 = 4:6)
    expand(df, groupid, c(itemid, itemname), keep = names(df))
    expand(df, groupid, c(itemid, itemname)) %>% left_join(df)

**Comment by hadley** [comment]
Why does it work better in chains? To two examples use exactly the same number of characters!

**Comment by blasern** [comment]
In the above case, yes. But if you have operations before the expand, you have to split the chain. The below example is still a bit artificial, but after a `summarize`, this may be rather useful.

    df <- data.frame(groupid = c(1:2, 1),
                     itemid = c(1:2, 2),
                     itemname = c("a", "b", "b"))
    # with keep argument
    df %>% mutate(value = 1:3) %>% expand(groupid, c(itemid, itemname), keep = names(df))
    # without keep argument
    df1 <- df %>% mutate(value = 1:3)
    df1 %>% expand(groupid, c(itemid, itemname)) %>% left_join(df1)

**Comment by hadley** [comment]
Or you can do:

```R
df %>% 
  mutate(value = 1:3) %>% 
  right_join(expand(., groupid, c(itemid, itemname)))
```

which doesn't seem that awful to me.

I feel like adding `keep` considerable dilutes the intent of `expand()`. OTOH it is a useful and common operation so I think it would appropriate as a new verb. Then you could also have some specification for what to replace with. Coming back to the SO question, it would be nice if you could do:

```R
df %>% expand_fill(itemid, groupid, value = 0)
```

(where `value` is the name of the variable where you want to replace NA with 0)

**Comment by garrettgman** [comment]
I suggest `expand_df`, `complete`, or `complete_df`. To me, it seems that this operation would add the missing combinations of key values to a data frame, which would reveal the implicit NAs contained in the data frame.

To keep it simple, the arguments can be the same as `expand` with the addition of `na.string` (as in `read.table`). Every column not listed in the arguments is joined to the `expand` output with the NAs in the requisite places.

Filtering the results or turning NAs into other characters afterwards seem like additional operations for additional code, but that's just my impression today :P

**Comment by hadley** [comment]
I like `complete()`.    NA replacement has be to column-by-column, because you might have variables of different types.  Maybe:

```R
df %>% complete(itemid, groupid, fill = list(value = 0))
```

**Comment by hadley** [comment]
It might be useful to have a replace missing function, since that is a common operation.  Then `complete()` = `expand()` + `left_join()` + `replace_na()`

**Comment by garrettgman** [comment]
I like the idea of a `replace_na` function!
