### ISSUE TITLE
tidying key-value pair columns

### ISSUE THREAD

**Issue by npjc** [hadley/tidyr#86]
### Synopsis
Many (biology) file formats / databases will have columns containing `key=value` pairs separated (`;`). Which are useful for storing (some obs may have many attributes, others may have none...) but not for working with. To work with them it is most convenient to tidy:

from:
```r
df
#> Source: local data frame [1 x 1]
#> 
#> attributes
#> 1 ID=enriched_region_1;Name=ACF1;Dbxref=modEncode:5056
```
to:
```r
#> Source: local data frame [1 x 3]
#> 
#> Dbxref                ID Name
#> 1 modEncode:5056 enriched_region_1 ACF1
```

__I am going back and forth between these two forms all the time and perhaps it's general enough that there should be a `tidyr` roundtrip set of functions for it?__

These would operate on a column of a `tbl` and take `inter` and `intra` (key value) separators. i.e. for the above:

```r
df %>%
  tidy_key_val_col(attributes, inter_sep = ';', intra_sep = '=')
```

### A minimal example:

```r
library(dplyr)
library(tidyr)

df <- data_frame(attributes = "ID=enriched_region_1;Name=ACF1;Dbxref=modEncode:5056")

#> Source: local data frame [1 x 1]
#> 
#> attributes
#> 1 ID=enriched_region_1;Name=ACF1;Dbxref=modEncode:5056
```

To tidy this up the general pattern is to:

```r
df %>% 
  mutate(attrs = stringi::stri_split_fixed(attributes, ';')) %>% 
  unnest(attrs) %>% 
  separate(attrs, c("attr_var", "attr_val"), '=') %>% 
  spread(attr_var, attr_val) %>% 
  select(-attributes)
#> Source: local data frame [1 x 3]
#> 
#> Dbxref                ID Name
#> 1 modEncode:5056 enriched_region_1 ACF1
```

**Comment by hadley** [comment]
Maybe this could be generalisation of #69?

**Comment by npjc** [comment]
I think you could argue the core of it is really:

`"key1=value1;key2=value2"` to `keys = c("key1", "key2"), values = c("value1", "value2")`

That is to say that the `spread` is not really part of it:

Thus the generalisation of `unnest_string()`:

```r
df %>%
  unnest_string(attributes, inter_sep = ';', intra_sep = '=') %>%
  spread(attributes_keys, attributes_vals)
```

where `unnest_string()` has the params:

- `tbl` tbl to operate on
- `var` variable column
- `inter_sep` separates key-value pairs (between)
- `intra_sep` separates key from value within a key-value pair (within). defaults to '='.
- `into` col_names for output --> defaulting to name of `var` + `c("_keys", "_vals")` .

**Comment by hadley** [comment]
Currently this feels a bit too special purpose for tidyr.
