### ISSUE TITLE
Conflict with reshape package

### ISSUE THREAD

**Issue by ldecicco-USGS** [hadley/tidyr#88]
Is there any way to fix the conflict caused by `reshape`?
```
library(tidyr)
df <- data.frame(x=rep("a",4),
                 y=c(1:3,NA),
                 key=c("g","g","c","d"),
                 stringsAsFactors = FALSE)
gather(df, variable, value, -key)
library(reshape)
gather(df, variable, value, -key)
```
I have tried recommending to not use the `reshape` package, but it still seems like an issue that could be fixed at the package level.

**Comment by hadley** [comment]
At some point tidyr will become self-contained and will no longer rely on reshape2. That will fix this problem.

**Comment by hadley** [comment]
Decided to go ahead and do this for the next version
