### ISSUE TITLE
When creating a variable with the same name as one of the original columns used in unite, the new column is removed (with remove = TRUE).

### ISSUE THREAD

**Issue by theunis** [hadley/tidyr#89]
For example:
```r
unite(mtcars, vs, vs, am)
```
removes both the *vs* and *am* column, while not creating a new column *vs*.
If this is intended functionality, perhaps a warning message would be appropriate.

**Comment by hadley** [comment]
It does create the column, but it then immediately removes it.   You're currently on your own in tidyr if you create multiple columns with the same name.
