### ISSUE TITLE
spread in parallel

### ISSUE THREAD

**Issue by halidaee** [hadley/tidyr#90]
Spread seems to have some type of issue running in parallel. 

I have the following code nested inside a function: 

```
 df <- df %>%
    arrange(time, EX, QTYPE) %>% 
    mutate(size = ifelse(QTYPE=='BID',BIDSIZ, OFRSIZ)) %>%
    arrange(time, EX, QTYPE)
####
df_nbbo <- df %>%
    filter(ifelse(QTYPE=='BID',best_bid_mkr == TRUE, best_ofr_mkr == TRUE)) %>%
    spread(QTYPE, QPRICE)
```
When my code is run serially, either using a for loop or as a function in lapply, I have the desired dataframe outputted by write.csv. However, when using %dopar% or mclapply, my dataframe is fine until the spread command (gather works just fine). 

No error gets produced by spread. I only uncovered the problem by doing write.csv at the end of each command until I ruled it down to spread. This happens to me twice by spread inside my code.

**Comment by hadley** [comment]
Please provide a minimal reproducible example.

**Comment by halidaee** [comment]
Issue seems to have gone away, and was device specific. I'll re-open if I come across it again, but it seems as if there was something conflicting with tidyr. Thanks!
