### ISSUE TITLE
pivot pairs of key-value variables using tidyr:spread()

### ISSUE THREAD

**Issue by ronencozen** [hadley/tidyr#94]
I am trying to pivot pairs of key-value variables using tidyr:spread() .

```R
id <- c(0,1,2,3,4,5,6,7,8,9)
key1 <- c("a", "a", "b", "b", "c","a", "a", "b", "b", "c")
val1 <- c(1,2,3,1,2,3,1,2,3,1)
key2 <- c("d",NA,NA,NA,"e","d","d",NA,"b",NA)
val2 <- c(1,NA,NA,NA,2,3,NA,NA,3,NA)
key3 <- c("x",NA,NA,NA,"e","d",NA,NA,NA,NA)
val3 <- c(0,NA,NA,NA,NA,3,1,NA,NA,NA)
df = data.frame(id, key1, val1, key2, val2, key3, val3) 
library(tidyr)
c1 <- spread(df, key1, val1, fill = 0, convert = FALSE)
c2 <- spread(c1, key2, val2, fill = 0, convert = FALSE)
c3 <- spread(c2, key3, val3, fill = 0, convert = FALSE) 
```

while running the spread(), i get the following error:

Error in [.data.frame(data, setdiff(names(data), c(key_col, value_col))) : undefined columns selected

It makes me think that the problem is incorrect NA handling ?

on the same token, is there a more syntax efficient way to spread multiple pair of key-value variables?

Thank you!

**Comment by jennybc** [comment]
I took a look at this because there was a recent [multi-spread question on stackoverflow](http://stackoverflow.com/questions/31687180/spread-multiple-coordinated-columns/31687741#31687741), but a good `tidyr` solution eludes me. This issue seems to be about something else anway.

But while I passed through here, I found this issue is more related to the creation of variables named `NA` due to the presence of `NA`s in a key variable. Which is (sort of) [#68]. Repeating the example in easier to read/run form.

```r
library(tidyr)

df <- data.frame(id = 0:9,
                 key1 = c("a", "a", "b", "b", "c","a", "a", "b", "b", "c"),
                 val1 = rep(1:3, length.out = 10),
                 key2 = c("d",NA,NA,NA,"e","d","d",NA,"b",NA),
                 val2 = c(1L,NA,NA,NA,2L,3L,NA,NA,3L,NA),
                 key3 = c("x",NA,NA,NA,"e","d",NA,NA,NA,NA),
                 val3 = c(0,NA,NA,NA,NA,3,1,NA,NA,NA)) 

(c1 <- spread(df, key1, val1, fill = 0, convert = FALSE))
```

```
##    id key2 val2 key3 val3 a b c
## 1   0    d    1    x    0 1 0 0
## 2   1 <NA>   NA <NA>   NA 2 0 0
## 3   2 <NA>   NA <NA>   NA 0 3 0
## 4   3 <NA>   NA <NA>   NA 0 1 0
## 5   4    e    2    e   NA 0 0 2
## 6   5    d    3    d    3 3 0 0
## 7   6    d   NA <NA>    1 1 0 0
## 8   7 <NA>   NA <NA>   NA 0 2 0
## 9   8    b    3 <NA>   NA 0 3 0
## 10  9 <NA>   NA <NA>   NA 0 0 1
```

```r
(c2 <- spread(c1, key2, val2, fill = 0, convert = FALSE))
```

```
##    id key3 val3 a b c b d e NA
## 1   0    x    0 1 0 0 0 1 0  0
## 2   1 <NA>   NA 2 0 0 0 0 0  0
## 3   2 <NA>   NA 0 3 0 0 0 0  0
## 4   3 <NA>   NA 0 1 0 0 0 0  0
## 5   4    e   NA 0 0 2 0 0 2  0
## 6   5    d    3 3 0 0 0 3 0  0
## 7   6 <NA>    1 1 0 0 0 0 0  0
## 8   7 <NA>   NA 0 2 0 0 0 0  0
## 9   8 <NA>   NA 0 3 0 3 0 0  0
## 10  9 <NA>   NA 0 0 1 0 0 0  0
```

```r
c3 <- spread(c2, key3, val3, fill = 0, convert = FALSE)
```

```
## Error in `[.data.frame`(data, setdiff(names(data), c(key_col, value_col))): undefined columns selected
```

```r
names(c2)[is.na(names(c2))] <- "NA"
(c3 <- spread(c2, key3, val3, fill = 0, convert = FALSE))
```

```
##    id a b c d e NA d e x NA
## 1   0 1 0 0 1 0  0 0 0 0  0
## 2   1 2 0 0 0 0  0 0 0 0  0
## 3   2 0 3 0 0 0  0 0 0 0  0
## 4   3 0 1 0 0 0  0 0 0 0  0
## 5   4 0 0 2 0 2  0 0 0 0  0
## 6   5 3 0 0 3 0  0 3 0 0  0
## 7   6 1 0 0 0 0  0 0 0 0  1
## 8   7 0 2 0 0 0  0 0 0 0  0
## 9   8 0 3 0 0 0  0 0 0 0  0
## 10  9 0 0 1 0 0  0 0 0 0  0
```

**Comment by ronencozen** [comment]
Hi Jenny,

Thanks for taking the time to provid a nice solution to the NA variables.
I run into a bigger problem, related to the outcome of the spread function which create duplicate variables.
In the example above variable "e" is such duplciate.
I would expect that spread function will know to collapse duplciate variables in runtime.

Thanks,

Ronen

**Comment by jennybc** [comment]
This aspect of your example surprises me, in that I'm surprised the duplicate variable names don't cause more trouble. But it's probably not realistic to expect the "collapse at runtime" you mention above. For example, it's not entirely clear how the two variables named `e` should be combined to make one variable.

**Comment by ronencozen** [comment]
Two or more duplicate variables should be combined and the values associated with insatnce of the variable should be summed up.
in our example  variable "e" appears twice ones with the value "2" and the second time with value "na", which is a typo in the example, it should be associated with a real value let's say "1", so the combined "e" has the value of "3" for a given row.

I would not say it is not a realistic request , by doing so you improve the spread function, make it more user friendly by dissolving complexity, instead of leaving the data in an unusable state, as in my example.

**Comment by hadley** [comment]
@ronencozen But why sum? There are lots of other ways you could aggregate multiple values.  The goal of each function in tidyr is to do one thing well, so I think it would be a bad idea to all do aggregation in `spread()`.

**Comment by ronencozen** [comment]
You are right on the theoretical level, in practice the key-value structure
is used to capture hierarchical relationships, e.g. bill of material.

the key-value structure is not semantic, and as such it needs to be pivoted
or spread, in order to be utilized in further analysis.

e.g.


Assembly

compenet 1

unit 1

component 2

unit 2

a

a1

1

a1

4

b

a1

2

NA

NA

after pivot:

Assembly

a1

a2

a

5

1

b

2



if you would like to keep the spread function alone, maybe you can
introduce a new function called pivot/unpivot to satisfy this very common
use case described above.

btw, an explicit NULL handling parameter should be introduced, with a
default to discard NAs to the spread().

HTH

ronen

**Comment by ronencozen** [comment]
i doubled check with the real example and the data situation depicted above
doesn't exit, meaning that for assembly a component a1 can't appear more
than once.
in other words if there are no duplicates spread() is doing what is
expected, so the only problem left is the NAs.

sorry for the false alarm.
