### ISSUE TITLE
unexpected spread behavior with NA values

### ISSUE THREAD

**Issue by kevinummel** [hadley/tidyr#95]
Behavior of spread() is unexpected when gathered data has missing variable combinations and NA values. Using example from ?spread :

```R
library(dplyr)
stocks <- data.frame(
  time = as.Date('2009-01-01') + 0:9,
  X = rnorm(10, 0, 1),
  Y = rnorm(10, 0, 2),
  Z = rnorm(10, 0, 4)
)

stocksm <- stocks %>% gather(stock, price, -time)

# Drop some rows from gathered data to create missing combinations of ‘time’ and ‘stock’
stocksm = stocksm[-sample(nrow(stocksm),3),]

# Add some NA values to the ‘price’ variable
stocksm$price[sample(nrow(stocksm),5)] = NA

# Spread the data, filling missing combinations with zeros via ‘fill’ argument
stocksm %>% spread(stock, price, fill=0)

         time          X            Y          Z
1  2009-01-01  0.7093746  1.137690258  7.3974182
2  2009-01-02  0.8048673  0.000000000  0.1827842
3  2009-01-03  0.4592391 -1.097792967 -2.5656054
4  2009-01-04  0.0000000  0.005282344  0.0000000
5  2009-01-05  1.2138317  3.443762442 -2.7865275
6  2009-01-06 -1.4190098  0.000000000  4.4084264
7  2009-01-07 -0.3652678 -1.288887308 -4.2625258
8  2009-01-08 -1.0465328  2.813266623  1.8301144
9  2009-01-09  0.0000000  0.000000000  5.9644504
10 2009-01-10  0.0000000  0.000000000  2.5544768
```

The expected behavior here is to preserve NA values in the output when they are present in the gathered/input data (the input data should never to violated) and use the ‘fill’ argument ONLY for missing combinations – indeed, this is what the current documentation implies. Instead, BOTH missing combinations and NA values are replaced with the ‘fill’ value.

**Comment by hadley** [comment]
Here's a simpler example:

```R
df <- data.frame(
  x = c("a", "a", "b"),
  y = c("a" , "b", "a"),
  z = c(1, 1, NA)
)

df %>% spread(x, z)
#>  y a  b
#> 1 a 1 NA
#> 2 b 1 NA
```

There are two types of missing value in the output - one is an explicit missing in the input and the other is an implicit missing in the input. 

You're asking to treat implicit and explicit missing values differently, which seems a little odd to me. I think that implies the documentation needs to change, not the code.

**Comment by kevinummel** [comment]
Hi Hadley,

See you've closed this. Would just point out that treating implicit and
explicit missing values differently is potentially very helpful in case of
(big) data that take strictly non-negative values. In that case, the
gathered data need only store positive (non-zero) values (and possibly
explicit NA), and the analyst uses spread(fill=0) to generate the "true"
output when wide form is required. Common example (for me) is large
household datasets.

Cheers,
Kevin

**Comment by hadley** [comment]
I think using implicit and explicit missings to mean different things is risky, so unfortunately tidyr isn't going to help. You should be able to build your own version of spread though.
